In [63]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\kush2\appdata\local\programs\python\python312\lib\site-packages (2.2.0)
Requirement already satisfied: numpy<2,>=1.26.0 in c:\users\kush2\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kush2\appdata\roaming\python\python312\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\kush2\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kush2\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2023.4)
Requirement already satisfied: six>=1.5 in c:\users\kush2\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [64]:
import pandas as pd
###port seaborn as sns

In [65]:
#read the dataset
data = pd.read_csv("NFD - Number of fires by cause class - EN FR.csv", encoding='latin-1')
data.head()

,Year,Année,ISO,Jurisdiction,Juridiction,Cause,Origine,Number,Data Qualifier,Nombre,Qualificatifs de données
0,1990,1990,AB,Alberta,Alberta,Human activity,Activités humaines,379.0,a,379.0,a
1,1990,1990,AB,Alberta,Alberta,Lightning,Foudre,971.0,a,971.0,a
2,1990,1990,AB,Alberta,Alberta,Unspecified,Indéterminée,16.0,a,16.0,a
3,1990,1990,BC,British Columbia,Colombie-Britannique,Human activity,Activités humaines,1240.0,a,1240.0,a
4,1990,1990,BC,British Columbia,Colombie-Britannique,Lightning,Foudre,2015.0,a,2015.0,a

In [66]:
data.drop("Année",axis=1)

,Year,ISO,Jurisdiction,Juridiction,Cause,Origine,Number,Data Qualifier,Nombre,Qualificatifs de données
0,1990,AB,Alberta,Alberta,Human activity,Activités humaines,379.0,a,379.0,a
1,1990,AB,Alberta,Alberta,Lightning,Foudre,971.0,a,971.0,a
2,1990,AB,Alberta,Alberta,Unspecified,Indéterminée,16.0,a,16.0,a
3,1990,BC,British Columbia,Colombie-Britannique,Human activity,Activités humaines,1240.0,a,1240.0,a
4,1990,BC,British Columbia,Colombie-Britannique,Lightning,Foudre,2015.0,a,2015.0,a
...,...,...,...,...,...,...,...,...,...,...
1054,2021,PC,Parks Canada,Parcs Canada,Unspecified,Indéterminée,73.0,e,73.0,e
1055,2021,PE,Prince Edward Island,Île-du-Prince-Édouard,Unspecified,Indéterminée,1.0,e,1.0,e
1056,2021,QC,Quebec,Québec,Unspecified,Indéterminée,625.0,e,625.0,e
1057,2021,SK,Saskatchewan,Saskatchewan,Unspecified,Indéterminée,635.0,e,635.0,e
1058,2021,YT,Yukon,Yukon,Unspecified,Indéterminée,112.0,e,112.0,e

In [67]:
#data.drop(['Juridiction','Année','Origine','Nombre','Qualificatifs de données'],axis = 1,inplace=True)

In [68]:
data2 = pd.read_csv("NFD - Area burned by fire size class - EN FR.csv", encoding='latin-1')
print(data2.head())
print(data2.shape)

   Year  Année ISO Jurisdiction Juridiction        Fire size class  \
0  1990   1990  AB      Alberta     Alberta          0.11 - 1.0 ha
1  1990   1990  AB      Alberta     Alberta            1.1 - 10 ha
2  1990   1990  AB      Alberta     Alberta  10 000.1 - 100 000 ha
3  1990   1990  AB      Alberta     Alberta          10.1 - 100 ha
4  1990   1990  AB      Alberta     Alberta       100.1 - 1 000 ha

  Classe de superficie à l'extinction  Area (hectares) Data Qualifier  \
0                         0,11 - 1 ha            171.0              a
1                         1,1 - 10 ha            504.0              a
2               10 000,1 - 100 000 ha          35809.5              a
3                       10,1 - 100 ha           1767.7              a
4                    100,1 - 1 000 ha           8179.1              a

   Superficie (en hectare) Qualificatifs de données
0                    171.0                        a
1                    504.0                        a
2                  35809.5                        a
3                   1767.7                        a
4                   8179.1                        a
(2394, 11)

In [69]:
#data2.drop(['Juridiction','Année',"Classe de superficie à l'extinction",'Superficie (en hectare)','Qualificatifs de données'],axis = 1,inplace=True)
data2.head()

,Year,Année,ISO,Jurisdiction,Juridiction,Fire size class,Classe de superficie à l'extinction,Area (hectares),Data Qualifier,Superficie (en hectare),Qualificatifs de données
0,1990,1990,AB,Alberta,Alberta,0.11 - 1.0 ha,"0,11 - 1 ha",171.0,a,171.0,a
1,1990,1990,AB,Alberta,Alberta,1.1 - 10 ha,"1,1 - 10 ha",504.0,a,504.0,a
2,1990,1990,AB,Alberta,Alberta,10 000.1 - 100 000 ha,"10 000,1 - 100 000 ha",35809.5,a,35809.5,a
3,1990,1990,AB,Alberta,Alberta,10.1 - 100 ha,"10,1 - 100 ha",1767.7,a,1767.7,a
4,1990,1990,AB,Alberta,Alberta,100.1 - 1 000 ha,"100,1 - 1 000 ha",8179.1,a,8179.1,a

In [70]:
data3 = pd.read_csv("NFD - Area burned by month - EN FR.csv",encoding = 'latin -1')
data3.head()
#data3.drop(['Juridiction','Année',"Mois",'Qualificatifs de données'],axis = 1,inplace=True)

,Year,Année,ISO,Jurisdiction,Juridiction,Month,Mois,Area (hectares),Data Qualifier,Superficie (en hectare),Qualificatifs de données
0,1990,1990,AB,Alberta,Alberta,January,Janvier,0.1,a,0.1,a
1,1990,1990,AB,Alberta,Alberta,October,Octobre,182.4,a,182.4,a
2,1990,1990,AB,Alberta,Alberta,November,Novembre,42.5,a,42.5,a
3,1990,1990,AB,Alberta,Alberta,December,Décembre,0.4,a,0.4,a
4,1990,1990,AB,Alberta,Alberta,February,Février,3.3,a,3.3,a

In [71]:
data3.head()

,Year,Année,ISO,Jurisdiction,Juridiction,Month,Mois,Area (hectares),Data Qualifier,Superficie (en hectare),Qualificatifs de données
0,1990,1990,AB,Alberta,Alberta,January,Janvier,0.1,a,0.1,a
1,1990,1990,AB,Alberta,Alberta,October,Octobre,182.4,a,182.4,a
2,1990,1990,AB,Alberta,Alberta,November,Novembre,42.5,a,42.5,a
3,1990,1990,AB,Alberta,Alberta,December,Décembre,0.4,a,0.4,a
4,1990,1990,AB,Alberta,Alberta,February,Février,3.3,a,3.3,a

In [72]:
data4 = pd.read_csv("NFD - Number of fires by fire size class - EN FR.csv",encoding = 'latin -1')
#data4.shape
#data4.drop(['Année','Juridiction',"Classe de superficie à l'extinction",'Nombre','Qualificatifs de données'],axis = 1,inplace=True)
data4.head()

,Year,Année,ISO,Jurisdiction,Juridiction,Fire size class,Classe de superficie à l'extinction,Number,Data Qualifier,Nombre,Qualificatifs de données
0,1990,1990,AB,Alberta,Alberta,0.11 - 1.0 ha,"0,11 - 1 ha",380.0,a,380.0,a
1,1990,1990,AB,Alberta,Alberta,1.1 - 10 ha,"1,1 - 10 ha",160.0,a,160.0,a
2,1990,1990,AB,Alberta,Alberta,10 000.1 - 100 000 ha,"10 000,1 - 100 000 ha",3.0,a,3.0,a
3,1990,1990,AB,Alberta,Alberta,10.1 - 100 ha,"10,1 - 100 ha",54.0,a,54.0,a
4,1990,1990,AB,Alberta,Alberta,100.1 - 1 000 ha,"100,1 - 1 000 ha",23.0,a,23.0,a

In [73]:
data5 = pd.read_csv("NFD - Number of fires by month - EN FR.csv",encoding = 'latin-1')
data5.head()
#data5.drop(['Juridiction','Année',"Mois",'Nombre','Qualificatifs de données'],axis=1,inplace=True)

,Year,Année,ISO,Jurisdiction,Juridiction,Month,Mois,Number,Data Qualifier,Nombre,Qualificatifs de données
0,1990,1990,AB,Alberta,Alberta,January,Janvier,1.0,a,1.0,a
1,1990,1990,AB,Alberta,Alberta,October,Octobre,34.0,a,34.0,a
2,1990,1990,AB,Alberta,Alberta,November,Novembre,16.0,a,16.0,a
3,1990,1990,AB,Alberta,Alberta,December,Décembre,4.0,a,4.0,a
4,1990,1990,AB,Alberta,Alberta,February,Février,5.0,a,5.0,a

In [74]:

#data5.drop(['Year','ISO',"Jurisdiction",'Month','Data Qualifier'],axis=1,inplace=True)
data5.head()

,Year,Année,ISO,Jurisdiction,Juridiction,Month,Mois,Number,Data Qualifier,Nombre,Qualificatifs de données
0,1990,1990,AB,Alberta,Alberta,January,Janvier,1.0,a,1.0,a
1,1990,1990,AB,Alberta,Alberta,October,Octobre,34.0,a,34.0,a
2,1990,1990,AB,Alberta,Alberta,November,Novembre,16.0,a,16.0,a
3,1990,1990,AB,Alberta,Alberta,December,Décembre,4.0,a,4.0,a
4,1990,1990,AB,Alberta,Alberta,February,Février,5.0,a,5.0,a

In [75]:
data6 = pd.read_csv("NFD - Property losses from fires - EN FR.csv",encoding = 'latin-1')
data6.head()
#data6.shape
#data6.drop(['Année','Juridiction','Zone de protection','Dollars (Fr)','Qualificatifs de données'],axis=1,inplace=True)

,Year,Année,ISO,Jurisdiction,Juridiction,Protection zone,Zone de protection,Dollars (En),Data qualifier,Dollars (Fr),Qualificatifs de données
0,1970,1970,AB,Alberta,Alberta,Intensive,Intensive,0.0,a,0.0,a
1,1970,1970,AB,Alberta,Alberta,Intensive,Intensive,NaN,n,NaN,n
2,1970,1970,BC,British Columbia,Colombie-Britannique,Intensive,Intensive,344684.0,a,344684.0,a
3,1970,1970,BC,British Columbia,Colombie-Britannique,Intensive,Intensive,NaN,n,NaN,n
4,1970,1970,MB,Manitoba,Manitoba,Intensive,Intensive,2002.0,a,2002.0,a

# Merege 2 dataframe

In [76]:
#frames = [data3,data5]
#result = pd.concat(frames,axis = 1)
#result.shape
#result.drop(['Année','Juridiction','Mois','Nombre','Qualificatifs de données','Superficie (en hectare)'],axis = 1)

In [77]:
#merged_data = pd.merge(data2, data4, on=['Year', 'ISO', 'Jurisdiction', 'Fire size class'], how='outer')
#merged_data

In [83]:

import pandas as pd

# Assuming 'data1', 'data2', 'data3', 'data4', 'data5', and 'data6' are the names of your dataframes

# Concatenate dataframes along rows (axis=0) based on common columns
merged_data = pd.concat([data.set_index(['Year', 'ISO', 'Jurisdiction']),
                        data2.set_index(['Year', 'ISO', 'Jurisdiction']),
                        data3.set_index(['Year', 'ISO', 'Jurisdiction']),
                        data4.set_index(['Year', 'ISO', 'Jurisdiction']),
                        data5.set_index(['Year', 'ISO', 'Jurisdiction']),
                        data6.set_index(['Year', 'ISO', 'Jurisdiction'])],
                       axis=1, join='outer', keys=['data1', 'data2', 'data3', 'data4', 'data5', 'data6'])

# Reset index to make the columns regular columns again
merged_data.reset_index(inplace=True)

# Filter out unnecessary columns
merged_data = merged_data[['Year', 'ISO', 'Jurisdiction', 
                           'data1_Cause', 'data2_Fire size class', 'data3_Month', 
                           'data4_Fire size class', 'data5_Number', 'data6_Protection zone', 'data6_Dollars (En)']]

# Display the merged dataset
print(merged_data.head())

C:\Users\kush2\AppData\Local\Temp\ipykernel_26740\1454712271.py:6: RuntimeWarning: The values in the array are unorderable. Pass `sort=False` to suppress this warning.
  merged_data = pd.concat([data.set_index(['Year', 'ISO', 'Jurisdiction']),

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [89]:
import pandas as pd

# Assuming 'data1', 'data2', 'data3', 'data4', 'data5', and 'data6' are the names of your dataframes

# Reset index for all dataframes
data1_reset = data.reset_index()
data2_reset = data2.reset_index()
data3_reset = data3.reset_index()
data4_reset = data4.reset_index()
data5_reset = data5.reset_index()
data6_reset = data6.reset_index()

# Concatenate dataframes along rows (axis=0) based on common columns
merged_data = pd.concat([data1_reset, data2_reset, data3_reset, data4_reset, data5_reset, data6_reset],
                       axis=1, join='outer', keys=['data1', 'data2', 'data3', 'data4', 'data5', 'data6'])

# Flatten the MultiIndex columns
merged_data.columns = ['{}_{}'.format(col[0], col[1]) for col in merged_data.columns]

# Filter out unnecessary columns
merged_data

,data1_index,data1_Year,data1_Année,data1_ISO,data1_Jurisdiction,data1_Juridiction,data1_Cause,data1_Origine,data1_Number,data1_Data Qualifier,...,data6_Année,data6_ISO,data6_Jurisdiction,data6_Juridiction,data6_Protection zone,data6_Zone de protection,data6_Dollars (En),data6_Data qualifier,data6_Dollars (Fr),data6_Qualificatifs de données
0,0.0,1990.0,1990.0,AB,Alberta,Alberta,Human activity,Activités humaines,379.0,a,...,1970.0,AB,Alberta,Alberta,Intensive,Intensive,0.0,a,0.0,a
1,1.0,1990.0,1990.0,AB,Alberta,Alberta,Lightning,Foudre,971.0,a,...,1970.0,AB,Alberta,Alberta,Intensive,Intensive,NaN,n,NaN,n
2,2.0,1990.0,1990.0,AB,Alberta,Alberta,Unspecified,Indéterminée,16.0,a,...,1970.0,BC,British Columbia,Colombie-Britannique,Intensive,Intensive,344684.0,a,344684.0,a
3,3.0,1990.0,1990.0,BC,British Columbia,Colombie-Britannique,Human activity,Activités humaines,1240.0,a,...,1970.0,BC,British Columbia,Colombie-Britannique,Intensive,Intensive,NaN,n,NaN,n
4,4.0,1990.0,1990.0,BC,British Columbia,Colombie-Britannique,Lightning,Foudre,2015.0,a,...,1970.0,MB,Manitoba,Manitoba,Intensive,Intensive,2002.0,a,2002.0,a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3192,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
# Assuming 'merged_data' is the DataFrame containing the merged data

# Specify the path where you want to save the CSV file
output_path = 'C:\\Users\\kush2\\OneDrive\\Desktop\\Hackathon\\Merged.csv'

# Save the DataFrame to a CSV file
merged_data.to_csv(output_path, index=False)

print(f'Merged data has been saved to {output_path}')

Merged data has been saved to C:\Users\kush2\OneDrive\Desktop\Hackathon\Merged.csv